maintenance: update k8s dependencies to latest patch version
digitalocean/digitalocean-cloud-controller-manager pull request #495
Opened 2022-08-11 10:48 UTC by mo-rieger

go get k8s.io/api@v0.24.3 k8s.io/apimachinery@v0.24.3 k8s.io/client-go@v0.24.3 k8s.io/cloud-provider@v0.24.3 k8s.io/component-base@v0.24.3
go mod tidy
go mod vendor

CLOSES: CON-7030

2022-08-11 11:31 UTC, timoreimann commented
@mo-rieger looks like our format checker is complaining about two files not being gofmt'ed: https://github.com/digitalocean/digitalocean-cloud-controller-manager/runs/7785308528?check_suite_focus=true#step:5:151

This seems unrelated to your PR and must have slipped through to master. Would you mind pushing a quick commit to fix it?

2022-08-16 09:20 UTC, mo-rieger commented
> 

The linting issue occurs only in the CI because set-up go installs the latest minor version of go. I fixed it to use the latest patch version of the go version used in the project.

2022-08-16 10:05 UTC, timoreimann requested changes

2022-08-16 10:21 UTC, mo-rieger commented on .github/workflows/release.yml
> +        uses: actions/setup-go@v3.1.0
Got it, changed it to use the commit SHA.

2022-08-16 10:35 UTC, timoreimann approved these changes
Thanks Moritz.

2022-08-16 12:03 UTC, cpanato approved these changes

2022-08-16 12:08 UTC, merged